language: node_js
node_js:
- '8'
script:
- npm test
before_install:
  provider: script
  script: bash scripts/setDeploymentKey.sh
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: do-deploy
