language: node_js
node_js:
- '8'
script:
- npm test
before_install:
  - openssl aes-256-cbc -K $encrypted_0eb8cab50dbb_key -iv $encrypted_0eb8cab50dbb_iv -in deploy-key.enc -out deploy-key -d
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: do-deploy
